openapi: 3.0.0
info:
  title: Student Management API
  description: API for managing student records
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Local development server
paths:
  /students:
    post:
      summary: Add a new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '201':
          description: Student created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '400':
          description: Invalid input
    get:
      summary: Get all students
      responses:
        '200':
          description: List of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
  /students/{id}:
    get:
      summary: Get a student by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Student details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '404':
          description: Student not found
    put:
      summary: Update a student by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Student updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '404':
          description: Student not found
    delete:
      summary: Delete a student by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Student deleted successfully
        '404':
          description: Student not found
components:
  schemas:
    Student:
      type: object
      required:
        - name
        - age
        - className
        - phoneNumber
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          example: Kshitij
        age:
          type: integer
          example: 25
        className:
          type: string
          example: 10th Grade
        phoneNumber:
          type: string
          example: "1234567890"